version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build completed. Zipping files...
      - zip -r nodejs-app.zip * .[^.]*

artifacts:
  files:
    - nodejs-app.zip