phases:
  install:
    commands:
      - set -x  # This enables debugging
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $ImageName -f ./Dockerfile .
  post_build:
    commands:
      - echo "Tagging Docker image"
      - docker tag $ImageName:latest 703671891941.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - echo "Pushing Docker image to ECR"
      - docker push 703671891941.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
